version: '3.3'
services:
  bills_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bills_portal'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    # volumes:
      # - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - bills_db
    environment:
      PMA_HOST: bills_db
      PMA_PORT: 3306
    ports:
      - '8080:80'
# Names our volume
# volumes:
  # data:
